### ISSUE TITLE
Update Dojo 2 projects to use grunt-dojo2-extras

### ISSUE THREAD

**Issue by devpaul** [dojo/grunt-dojo2-extras#14]
We need to update the [Dojo 2 projects](http://dojo.io/api/) to use grunt-dojo2-extras.

Each project will need the following:

* add grunt-dojo2-extras
    * add `init`, `prepublish`, `publish`, and `api` tasks
    * add a new deploy_key.enc using `grunt init` (requires permissions)
* remove grunt-dojo2 usage
    * remove `doc` task
    * remove `typedoc` and related tasks from grunt-dojo2 repository
* update .travis.yml
    * remove openssl `before_install` task ([example](https://github.com/dojo/core/blob/a08ef39f323817a9a896a9a425f55e33a634ab4c/.travis.yml#L16-L19))
    * add a deploy task that calls `grunt publish` ([example](https://github.com/dojo/grunt-dojo2-extras/blob/master/.travis.yml#L12-L17))
* set up Travis
    * Add DEPLOY_DOCS=publish when ready to publish (requires permission)

We can use grunt-dojo2-extras as an example project as it uses itself to self-publish

**Comment by dylans** [comment]
Not sure this is still needed... feel free to reopen if it is.
