### ISSUE TITLE
Upgrade Typedoc to use TypeScript 2.3.2 

### ISSUE THREAD

**Issue by devpaul** [dojo/grunt-dojo2-extras#23]
The next release of TypeDoc should provide TypeScript 2.3.2 support. Since Dojo 2 has already switched to TS 2.3.2 we should update as well when TypeDoc releases.

**Comment by devpaul** [comment]
I tested using the latest (unreleased) typedoc on widget-core and it builds documentation without issue. Further progress is blocked until typedoc releases to npm.

**Comment by maier49** [comment]
This is now using the latest version of TypeDoc, and TypeScript 2.4.2. None of the other described changes have been made.

**Comment by maier49** [comment]
The remaining comments have been addressed or moved to other issues.
